apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: thalescpl/unitainer/dpod
    docker:
      dockerfile: docker/Dockerfile.dpod
    context: .
deploy:
  helm:
    releases:
    - name: dpod-p11tool
      chartPath: charts/dpod-p11tool
      values:
        image: thalescpl/unitainer/dpod
