apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: gcr.io/thales-cplcto/unitainer/hello_cloud
      docker:
        dockerfile: docker/Dockerfile.partition1
      context: .
deploy:
  helm:
    releases:
      - name: dpod-p11tool
        chartPath: charts/dpod-p11tool
        values:
          image.repository: gcr.io/thales-cplcto/unitainer/hello_cloud
